// export const baseURL = 'http://localhost:5000'
export const baseURL = 'https://spring-api-handler-production.up.railway.app'
export const YURIDAN = 'https://yuridan-production.up.railway.app'
export const CHARLIE = 'https://charlie-production-655b.up.railway.app'

export const loginUrl = baseURL + '/login'
export const karyawanAllUrl = baseURL + '/karyawan/all'
export const karyawanIdUrl = baseURL + '/karyawan/'
export const registerUrl = baseURL + '/registration'
export const updateUrl = baseURL + '/karyawan/update/'
export const deleteUrl = baseURL + '/karyawan/delete/'
export const createKaryawanUrl = baseURL + '/karyawan/create'
